project:
  type: book
  output-dir: docs

book:
  title: "remote sensing learning diary"
  author: "Norah Jones"
  date: "1/25/2024"
  chapters:
    - index.qmd
    - introduction.qmd
    - week1.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: Remote Sensing.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

