# Policy 

## Summary

-   The summary criterion will refer to the summary of the policy and city you have selected.

Rasjahi is one of the major urban centres in Bangaldesh with a population of around 500,000 people. It is located in the west of the country on the Indian-Bangladesh border and part of the Barind Tract, an area that experiences hot and dry climate. The most pressing climate challenges in the city are flooding during the monsoon season due to inadequate drainage system as well as extreme and dangerous heat.

According to the Word Health Organisation, heatwaves are among the deadliest climate risk globally. In fact, more than 166 000 people died due to extreme temperatures between 1998-2017 (<https://www.who.int/health-topics/heatwaves#tab=tab_3>). In cities heat stress can be exacerbated due to so called urban heat island effects (UHI). UHI is a phenomenon where urban areas experience higher temperatures compared to their surrounding rural areas due to human activities and the way the city is built (e.g. heat retention in buildings, infrastructure, sealed surfaces). With climate change temperatures in Bangladesh are expected to increase and extreme weather events, such as heat waves, are expected to become more frequent and more intense.

At the national level, the Government of Bangladesh has acknowledged the risk posed by increasing heat. In its National Adaptation Plan (2023), haet features as an adaptation priority or urban areas in its National Adaptation Plan. One of the action items in the urban area strategy of the NAP is to develop "heatwave and disease outbreak advisory services for city dwellers". No further guidance on how to tackle heat in cities is given and it is up to the local level governments to improve heat risk planning.

At the local level in Rajshahi, the City Cooperation has understood the importance of including climate change related hazards, icluding heat, into urban management. In recent years they have developed three important plans:

1.  A Masterplan that incorporate climate change issues (not publicly available, therefore will not discuss further),
2.  A Climate Resilient Action Plan (CAP) (developed with ICLEI), and
3.  A heat threshold assessment in the city (developed by Red Cross Red Crescent Climate Center).

The ICLEI CAP provides a high level climate risk assessment. It decribes UHI as an issue in the city but not spatially. Therefore, suggested mitigation and adaptation actions on heat remain vague.

The RCRC CC study expands ICLEI's work by looking more closely at urban heat in the city and mapping it spatially. The authors used Landsat images between 2010 to 2020 to map Land Surface Temperature in the city to identify heat hotspots and Normalised difference water index (NDWI) and normalised difference vegetation index (NDVI) to analyse the relationship between landcover changes and urban heat island effect (UHI). The findings are combined with demographic and socio-economic data to understand vulnerability. However, the demographic and socio-economic datasets from the national cencus are only available by ward. To develop specific actions for mitigating and adapting to the identified hotpots, we need data on the neigbourhood, street and building level.

I see two ways on how we can take the RC RCCC study forward to help the City Cooperation better mitigate and adapt to extreme heat:

-   Forcast heat stress and cccounting for the effects climate change applying different climate change scenarios according to the IPCC.

-   Using remote sensing data to improve the vulnerability assessment by identifying informal settlements with poor housing conditions where residents are at high risk of heat stress.

## Application

-   The application criterion will refer to how the remotely sensed data you sourced could be used to assist with contributing to the policy goal.

I will focus on the latter, identifying informal settlements, because it is an application area of remote sensing that I have always found interesting and I am keen to understand better how it is done. ... well, turns out its also "a mammoth task due to the spatial heterogeneity of urban landscape components, requiring complex analytical processes." @matariraGoogleEarthEngine2022 I chose two papers with different case studies to see how its done.

1.  ***Durban in South Africa***

The study uses Google Earth Engine to process Sentinel 2 images of the city of Durban integrating spectral and textural features in order to understand the extent and location of informal settlements. The paper investigates different data input combinations in order to find the one that presents most accurate and reliable findings. The study found that a classification based on spectral bands and textural information has the highest accuracy. It was able to detect informal settlements with a 80% accuracy.

The study used, multiple Sentinel 2A images from August 2020 with cloud cover \> 10% were. 3 images were selceted to form a composite, and a median value was assigned to each pixel, resulting in a single image used for processing.

The method used was pretty complex and I didnt understand it fully. I still summarized the key steps below, which I found useful as it gave me a rough understanding of the workflow and effort of such an analysis. Broad steps of the method listed below:

1.  Extraction of spectral and texture features from Sentinel 2A bands,
2.  Establishing different combinations of these feature types to be tested,
3.  Random Forest Classification using GGE,
4.  Replication of understand accuracy of the classier's perfromance, (20 classification results were obtained for each input feature set).
5.  Performance evaluation of feature subsets through a comparison of classification results of different feature subsets against the original feature set from which they were derived in order to establish if feature reduction would significantly improve informal settlement identification or not.
6.  Accuracy assessment to develop the relative comparative performances of different feature sets, against the benchmark experiment and was tested using Pixel-Based Accuracy Assessment and patch based.
7.  Regression between Extracted Informal Settlement Areas and Ground Truth Data.

@matariraGoogleEarthEngine2022

1.  ***Jakarta in Indonesia***

2.  **Using open data to detect the structure and pattern of informal settlements: an outset to support inclusive SDGs\' achievement**

## Reflection

-   How could the data be applied to solve the policy challenge. The reflection criterion will refer to what you have learnt in relation to the policy, city and the application of the data.
