# Xaringan Presentation and Quarto Book

This week is a little different and does not follow the usual structure of summary, application and reflection. We looked at the tools to make presentations and websites with code. For presentations, we can use Xaringan and for Books/Websites Quarto. This website is made with Quarto in R Studio and I set it up during week 2. Below you'll find a short presentation on Sentinel-2, which i made using Xaringan.

```{=html}
<iframe src="https://viktoriapues.github.io/w2_presentation/#1" width="800" height="600"></iframe>
```

Reflective note on making this presentation: It took me a while to get started with Xaringan. Once I got the hang of it, I loved how easy it is to change the style of the presentation.  It also seems to be a great tool to make your presentations look more streamlined. However, tbh, ppt is also really good at that and most people can use it. If you work in teams of coders and non-coders (which is most often the case in urban planning projects), it's not helpful to use tools that are not easily accessible to non coders. 
